alias gb="git branch"
alias gba="git branch -a"
alias gc="git checkout"
alias gcm="gs master"
alias gcma="ls | xargs -P10 -I{} git -C {} checkout master"
alias ga="git add"
alias gaa="git add -A"
alias gp="git push"
alias gpa="git push --all -u"
alias gs="git status"
alias gss="git status -s"
alias gl="git pull"
alias gla="ls | xargs -P10 -I{} git -C {} pull"
alias gpp="git config user.name CodyCoach; git config user.email coach.sathik@gmail.com"

# Git Client
alias fork="fork_cli"
