alias ion="ionic"
alias ionr="ionic serve"
alias ionrl="ionic lab"
alias ionra="ionic cordova run android --livereload"
alias ionri="ionic cordova run ios --livereload"
alias ionl="cordova run -list"
alias iongp="ionic g page"